# Generated by Django 3.0.2 on 2020-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('model', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citiesAv', models.CharField(max_length=2400)),
                ('phone', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('openHr', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('firstContent', models.CharField(max_length=2400)),
                ('secondContent', models.CharField(max_length=2400)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2400)),
            ],
        ),
    ]
