# Generated by Django 3.0.2 on 2020-01-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='citiesAv',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='openHr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='firstContent',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='secondContent',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
