# Generated by Django 3.0.2 on 2020-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200111_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
