# Generated by Django 3.0.2 on 2020-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='facebookLink',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='footerDescription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='instagramLink',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='snapchatLink',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='twitterLink',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
