# Generated by Django 3.0.2 on 2020-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200118_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
